# Generated by Django 3.2.25 on 2024-03-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordermain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordersub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.ordermain')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=100)),
                ('Offer_Price', models.CharField(default='', max_length=100)),
                ('Colour', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Dimensions', models.CharField(max_length=100)),
                ('Primary_Material', models.CharField(max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('Image1', models.CharField(default='', max_length=100)),
                ('Image2', models.CharField(default='', max_length=100)),
                ('CATEGORY', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.login')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('date', models.DateField(default='11-02-2024')),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.login')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('ORDERSUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.ordersub')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.user')),
            ],
        ),
        migrations.AddField(
            model_name='ordersub',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.product'),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.user'),
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type', models.CharField(max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Colour', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('Quantity', models.BigIntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=300)),
                ('Status', models.CharField(default='', max_length=100)),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('complaint', models.CharField(max_length=1000)),
                ('Reply', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=500)),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.product')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.product')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='', max_length=100)),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=100)),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('Duration', models.CharField(max_length=100)),
                ('Priority', models.CharField(max_length=100)),
                ('CUSTOMIZATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.customization')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.staff')),
            ],
        ),
    ]
