# Generated by Django 3.2.25 on 2024-03-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CATEGORY',
        ),
        migrations.AddField(
            model_name='product',
            name='SUBCATEGORY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Furniture_shopping.subcategory'),
        ),
    ]
