# Generated by Django 3.2.25 on 2024-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_shopping', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
