"""
URL configuration for untitled project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from Furniture_shopping import views

urlpatterns = [
    path('login/', views.login),
    path('login_post/', views.login_post),
    path('StaffRegistration/', views.StaffRegistration),
    path('StaffRegistration_post/', views.StaffRegistration_post),
    path('delete_staff/<id>', views.delete_staff),
    path('EditStaff/<id>', views.EditStaff),
    path('EditStaff_post/', views.EditStaff_post),
    path('ViewStaff/', views.ViewStaff),
    path('ViewStaff_post/', views.ViewStaff_post),
    path('AddCategory/', views.AddCategory),
    path('AddCategory_post/', views.AddCategory_post),
    path('ViewCategory/', views.ViewCategory),
    path('ViewCategory_post/', views.ViewCategory_post),
    path('delete_category/<id>', views.delete_category),
    path('EditCategory/<id>', views.EditCategory),
    path('staff_home/', views.staff_home),
    path('logout/', views.logout),
    path('Add_Product/', views.Add_Product),
    path('Add_Product_post/', views.Add_Product_post),
    path('ViewProduct/', views.ViewProduct),
    path('ViewProduct_post/', views.ViewProduct_post),
    path('EditProduct/<id>', views.EditProduct),
    path('Edit_Product_post/', views.Edit_Product_post),
    path('delete_product/<id>', views.delete_product),
    path('Stock/', views.Sstock),
    path('Stock_post/', views.Stock_post),
    path('ViewStock/', views.ViewStock),
    path('ViewStock_post/', views.ViewStock_post),
    path('admin_home/', views.admin_home),
    path('ViewUser/', views.ViewUser),
    path('ViewUser_post/', views.ViewUser_post),
    path('UserRegistration_post/', views.UserRegistration_post),
    path('ViewProfile_post/', views.ViewProfile_post),
    path('EditUser_post/', views.EditUser_post),
    path('Login_post/', views.Login_post),
    path('UserViewCategory/', views.UserViewCategory),
    path('UserViewSubCategory/', views.UserViewSubCategory),
    path('UserViewProductHome/', views.UserViewProductHome),
    path('UserViewProduct/', views.UserViewProduct),
    path('CustomizationRequest_post/', views.CustomizationRequest_post),
    path('ViewRequest/', views.ViewRequest),
    path('ViewRequest_post/', views.ViewRequest_post),
    path('accept_request/<id>', views.accept_request),
    path('reject_request/<id>', views.reject_request),
    path('ViewRequestStatus_post/', views.ViewRequestStatus_post),
    path('ViewAcceptedRequest/', views.ViewAcceptedRequest),
    path('ViewAcceptedRequest_post/', views.ViewAcceptedRequest_post),
    path('get_available_trailers/', views.get_available_trailers),
    path('AssignWorks/<id>', views.AssignWorks),
    path('AssignWorks_post/', views.AssignWorks_post),
    path('ViewWorks/', views.ViewWorks),
    path('ViewWorks_post/', views.ViewWorks_post),
    path('AddCart_post/', views.AddCart_post),
    path('user_viewcart/', views.user_viewcart),
    path('SendComplaint_post/', views.SendComplaint_post),
    path('ViewReply_post/', views.ViewReply_post),
    path('AdminViewComplaint/', views.AdminViewComplaint),
    path('AdminViewComplaint_post/', views.AdminViewComplaint_post),
    path('user_makepayment/', views.user_makepayment),
    path('user_removecart/', views.delete_cart),
    path('UpdateWork_post/<id>', views.UpdateWork_post),
    path('forgotpassword_post/', views.forgotpassword_post),
    path('forgotpassword/', views.forgotpassword),
    path('ViewOrderStatus_post/', views.ViewOrderStatus_post),
    path('user_change_password/', views.user_change_password),
    path('UserViewHomeCategory/', views.UserViewHomeCategory),
    path('UpdateWorks/<id>', views.UpdateWorks),
    path('UpdateWorks_post/', views.UpdateWorks_post),
    path('sendcomplaintandviewstatus_POST/', views.sendcomplaintandviewstatus_POST),
    path('viewreply_POST/', views.viewreply_POST),
    path('viewcomplaint/', views.viewcomplaint),
    path('viewcomplaint_POST/', views.viewcomplaint_POST),
    path('sendreply/<id>', views.sendreply),
    path('sendreply_POST/', views.sendreply_POST),
    path('staff_view_profile/', views.staff_view_profile),
    # path('staff_view_profile_post/', views.staff_view_profile_post),
    path('staff_edit_profile/', views.staff_edit_profile),
    path('staff_edit_profile_post/', views.staff_edit_profile_post),
    path('staff_payment_status/', views.staff_payment_status),
    path('view_paymentstatus_search/', views.view_paymentstatus_search),
    # path('generate_pdf_award/', views.generate_pdf_award),
    path('forgot_pass/', views.forgot_pass),
    path('ForgotPassword_Post/', views.ForgotPassword_Post),
    path('Order_main/', views.Order_main),
    path('Order_sub/<id>', views.Order_sub),
    path('generate_pdf/<id>', views.generate_pdf),
    path('ViewOrderMain_post/', views.ViewOrderMain_post),
    path('ViewOrderSub_post/', views.ViewOrderSub_post),
    path('delete_request/<id>', views.delete_request),
    path('delete_acceptedrequest/<id>', views.delete_acceptedrequest),
    path('delete_payment/<id>', views.delete_payment),
    path('View_single_product/', views.View_single_product),
    path('AddSubCategory/<id>', views.AddSubCategory),
    path('AddSubCategory_post/', views.AddSubCategory_post),
    path('ViewSubCategory/<id>', views.ViewSubCategory),
    path('ViewSubCategory_post/', views.ViewSubCategory_post),
    path('StaffViewCategory/', views.StaffViewCategory),
    path('StaffViewCategory_post/', views.StaffViewCategory_post),
    path('StaffViewSubCategory/<id>', views.StaffViewSubCategory),
    path('StaffViewSubCategory_post/', views.StaffViewSubCategory_post),
    path('User_Review/', views.User_Review),
    path('ViewReview/', views.ViewReview),
    path('Feedback_post/', views.Feedback_post),
    path('AdminViewFeedback/', views.AdminViewFeedback),
    path('AdminViewFeedack_post/', views.AdminViewFeedack_post),
    path('delete_ordermain/<id>', views.delete_ordermain),

]
